### ISSUE TITLE
enchantment support

### ISSUE THREAD

**Issue by Eclik1** [JongWasTaken/moretools#2]
Hey, nice datapack!
 
Just curious if enchantments like mending and unbreaking are supposed to be usable for the items or if that feature does not exist. 
I'm using version 1.2.0 on a fabric 1.20.6 server.

Thanks for everything!

**Comment by JongWasTaken** [comment]
Hello,

tools are supposed to inherit their enchantibility from their base tool (e.g. Hammers from Pickaxes).

I just now noticed that for some reason, they cannot be enchanted using an enchantment table.
This was not something i had tested before, since enchanting using books at an anvil works fine.

I will investigate this issue and publish a fix; In the meantime please enchant your tools using enchanted books.

Thank you for creating an issue for this!

**Comment by JongWasTaken** [comment]
I pushed a new update that should hopefully fix this issue. It also greatly improves compatibility with other polymer mods.
Version 1.3 is already available on Modrinth. It should become available in a few hours on CurseForge.

**Comment by Gregory-Jagermeister** [comment]
Hi Hate to be a pain but...

I think Version 1.4  for mc 1.21 has broken enchanting again at least for hammers, cant seem to enchant by either table or books. downloaded the repo to see if it was happening and it was. In the enchantment table all i get is efficiency and no other enchants. when trying to enchant via anvil it works in creative but not survival.

**Comment by JongWasTaken** [comment]
Actually, it looks like they split enchantment tags into groups, which seems to be the issue. I added all tools to the "durability" group and the "mining_loot" group, and I am now able to get enchantments like unbreaking and silk touch at an enchantment table.  
I will build and upload a hotfix release now, which should have this issue fixed (hopefully).

**Comment by Gregory-Jagermeister** [comment]
Hey Just tested,

Works Well!! Thanks a lot. hopefully Mojang doesn't break enchants again. its nice that i have a way to deal with durability getting eaten up so quick haha
